import { AssetList, Chain } from '@chain-registry/types';
import { EndpointOptions, LogLevel, MainWalletBase, NameServiceName, SessionOptions, SignerOptions, WalletConnectOptions, WalletModalProps } from '@cosmos-kit/core';
import { ReactNode } from 'react';
import { ThemeCustomizationProps } from './modal';
import { defaultModalViews } from './modal/components/views';
export declare const ChainProvider: ({ chains, assetLists, wallets, walletModal, modalViews, throwErrors, defaultNameService, walletConnectOptions, signerOptions, endpointOptions, sessionOptions, logLevel, children, modalTheme, }: {
    chains: Chain[];
    assetLists: AssetList[];
    wallets: MainWalletBase[];
    walletModal?: (props: WalletModalProps) => JSX.Element;
    modalViews?: typeof defaultModalViews;
    throwErrors?: boolean;
    defaultNameService?: NameServiceName;
    walletConnectOptions?: WalletConnectOptions;
    signerOptions?: SignerOptions;
    endpointOptions?: EndpointOptions;
    sessionOptions?: SessionOptions;
    logLevel?: LogLevel;
    children: ReactNode;
    modalTheme?: ThemeCustomizationProps;
}) => JSX.Element;
